add namespace warnings
redhat-cop/tower_utilities pull request #165
Opened 2023-05-08 00:34 UTC by sean-m-sullivan

# What does this PR do?
add namespace warnings to cop legacy branch

2023-05-08 13:05 UTC, djdanielsson requested changes
infra.controller_configuration to infra.aap_utilities

2023-05-08 13:05 UTC, djdanielsson commented on roles/aap_backup/tasks/main.yml
> +    msg: WARNING!!! You are using a version of redhat_cop.aap_utilities that is no longer maintained please change to infra.controller_configuration.
change to infra.aap_utilities

2023-05-08 20:09 UTC, djdanielsson approved these changes
LGTM

2023-05-09 14:16 UTC, Tompage1994 approved these changes

2023-05-10 01:30 UTC, merged