Add support for new platform installation method of AAP 2.5 on OpenShift
redhat-cop/tower_utilities pull request #261
Opened 2024-11-21 03:04 UTC by derekwaters

# What does this PR do?

This PR modifies the aap_ocp_install role to support the new platform installation method introduced to the AAP operator in AAP 2.5. It is backward 

# How should this be tested?

Requires an OpenShift cluster with appropriate credentials, then run:

```
      ansible.builtin.include_role:
        name: "infra.aap_utilities.aap_ocp_install"
```

with configuration as specified in the README and vars files defined in the role. 

Once complete, installation can be validated by accessing AAP via the quick links toolbar menu option.

# Is there a relevant Issue open for this?

https://github.com/redhat-cop/aap_utilities/issues/260
resolves #260 

# Other Relevant info, PRs, etc

None

2024-11-21 21:30 UTC, djdanielsson submitted a review, later dismissed
there is at least one change that needs to happen, I don't have OCP to test this so I will wait for someone who does to review and approve or not

2024-11-21 21:30 UTC, djdanielsson commented on galaxy.yml
> +version: 1.0.0
this is not correct

2024-11-21 21:35 UTC, derekwaters commented on galaxy.yml
> +version: 1.0.0
@djdanielsson I thought so too, but the pre-commit tests seemed to be flagging that as an issue? I'll change it back.

2024-11-21 22:13 UTC, djdanielsson commented on galaxy.yml
> +version: 1.0.0
It might not like the devel but we want to keep that because of how we have stuff working if pre-commit doesn't like it then ignore it

2024-11-21 23:04 UTC, branic commented
I'm planning on reviewing and testing, I'll should be able to get to it in the next day or two.

2024-12-06 21:50 UTC, branic requested changes
@derekwaters Thank you for your patience with me reviewing this PR.

I'd liek to request a couple of changes. I've been to get a working installation, but so far have not been successful. The Operator is installed and working and I've been able to get a platform manifest created and it started with a controller defined, but for several minutes after the playbook completes the web ui fails during login (I think because the controller instance is not ready yet). So I think there needs to be some other checks to ensure that the system is ready to be used before the playbook ends.

Also, it would be good to support installing into a different namespace than the operator is installed in.

I'm still getting my head around how the 2.5 install works and will provide more feedback.

One last request is to add an example playbook for installing the 2.5 version. Maybe relabel the existing example to be 2.4 and below and the new example as 2.5 and above.

2024-12-14 05:03 UTC, derekwaters commented
This PR has been updated to include:

1) The ability to install the operator and the platform in separate namespaces (when cluster-scoped operator channel is used)
2) Additional checks for controller / eda / hub API availability before proceeding with the playbook
3) Updated README to include separate example playbooks for 2.4 and earlier, and 2.5 and later

2025-01-10 20:28 UTC, djdanielsson commented
@branic have you had time to test it?

2025-01-11 00:40 UTC, branic requested changes
@derekwaters This PR is looking good. I like the changes you've made after the last review. I've got a few more comments and requests and I think this PR will be good to merge.

P.S. Sorry for not seeing this sooner and getting the review done. 
P.P.S @djdanielsson thanks for the ping.

2025-01-11 00:40 UTC, branic commented on roles/aap_ocp_install/README.md
> +| storage_type                       |          | file                             | Hub storage type (file, S3 or azure)*                             |
The default value isn't being taken into account. For example if specifying an instance name like:
```
    aap_ocp_install_hub:
      instance_name: tst-hub
```

The an error is encountered that the storage_type must be set:
```
TASK [infra.aap_utilities.aap_ocp_install : Ensure no validation errors found] ****************************************************************************
fatal: [localhost]: FAILED! => {
    "msg": [
        "The following errors must be fixed to continue:",
        [
            "aap_ocp_install_hub['storage_type'] must be 'file', 'S3' or 'azure'"
        ]
    ]
}
```

2025-01-11 00:40 UTC, branic commented on roles/aap_ocp_install/README.md
> +| object_storage_azure_secret        |          | None                             | Name of an OpenShift Secret used to access Azure storage for hub* |
I think it would be clearer (and match other parts of the readme) if the `*` was moved to the `Required` column instead of being at the end of the description.

2025-01-11 00:40 UTC, branic commented on roles/aap_ocp_install/README.md
> +| channel                          | Yes       | None          | Channel to subscribe (e.g. stable-2.2 or stable-2.2-cluster-scoped)*|
I think it would be clearer (and match other parts of the readme) if the `*` was moved to the `Required` column instead of being at the end of the description.

NOTE: This applies to other sections where the `*` is in the description column.

2025-01-11 00:40 UTC, branic commented on roles/aap_ocp_install/README.md
> +
A similar `*` note should also be made for the `instance_name` and `link_text` name in the tables for each component key.

Also, this note and notes in other sections needs to include `namespace` as well as that is ignored in a platform install and all installed components are installed in the platform namespace.

2025-01-11 00:40 UTC, branic commented on roles/aap_ocp_install/README.md
> +
Let's just get rid of these two lines. I don't think they are necessary and are just from the template.

2025-01-11 00:40 UTC, branic commented on roles/aap_ocp_install/README.md
> +    aap_ocp_install_eda: true
Setting these to `true` isn't obvious in the sections above for each key.

I wonder if it wouldn't be clearer to have something like an `install` key in the dictionary that is set to true or false. So that the usage is similar across versions. The `install` key could also be added to the the `aap_ocp_install_hub` dictionary so they all functioned similarly.

2025-01-11 00:40 UTC, branic commented on roles/aap_ocp_install/README.md
> +| aap_ocp_install_lightspeed                   | No       | None          | Indicates whether to install the Lightspeed component in an AAP platform installation        |
Need to specify that this is only applicable to 2.5+ platform install and what the acceptable values are and that the default is false.

2025-01-11 00:40 UTC, branic commented on roles/aap_ocp_install/tasks/install-platform.yml
> +  delay: 15
This check is failing for me. Doing a get of the Hub route with `/api` returns a `status_code` of 404. However, using a path of `/api/galaxy/pulp/api/v3/` returns a 200 `status_code` and allows the task to complete.

2025-01-11 00:40 UTC, branic commented on roles/aap_ocp_install/tasks/pre-validate.yml
> +                                  or (( __aap_ocp_install_major_version | int) == 2 \
To fix an ansible-lint warning:

```suggestion
                                  or ((__aap_ocp_install_major_version | int) == 2 \
```

2025-01-11 00:40 UTC, branic commented on roles/aap_ocp_install/tasks/pre-validate.yml
> +                                  and ( __aap_ocp_install_minor_version | int) >= 5) }}"
To fix an ansible-lint warning:

```suggestion
                                  and (__aap_ocp_install_minor_version | int) >= 5) }}"
```

2025-01-11 00:40 UTC, branic commented on changelogs/fragments/add_eda_install_on_ocp.yaml
> +  - Added ability to install EDA Controller on OCP
This changelog fragment and filename don't describe what change this PR is actually making.

2025-01-11 00:40 UTC, branic commented on roles/aap_ocp_install/tasks/pre-validate-platform.yml
> +  when: aap_ocp_install_hub is defined
If the intention is to default the `storage_type` to `file` (which I think is a good default). Then this when clause should only be checked when a `storage_type` is defined.

```suggestion
  when: aap_ocp_install_hub['storage_type'] is defined
```

2025-01-14 11:43 UTC, derekwaters commented on changelogs/fragments/add_eda_install_on_ocp.yaml
> +  - Added ability to install EDA Controller on OCP
That fragment is from a previous PR (which I happened to write). I assume the fragments get compiled into the full changelog at some point? Do the fragment files get removed? I've added a new fragment for the OCP AAP2.5 update.

2025-01-14 16:51 UTC, branic commented on changelogs/fragments/add_eda_install_on_ocp.yaml
> +  - Added ability to install EDA Controller on OCP
The fragments do get compiled into the full changelog and removed when a new version of the collection is published. Looking at the commits for this PR there are commits from the other PR that added the installation of EDA. You may need to take a look at the commit history for this PR/branch and rebase it and cleanup the commits that are included.

2025-01-14 20:07 UTC, derekwaters commented on changelogs/fragments/add_eda_install_on_ocp.yaml
> +  - Added ability to install EDA Controller on OCP
Yeah, you're right, sorry, that's my mistake. I'll get rid of this file.

2025-01-15 03:19 UTC, derekwaters commented on roles/aap_ocp_install/tasks/install-platform.yml
> +  delay: 15
Yes, you're right, that's the endpoint exposed through the hub route (I think I was using the one on the platform route). Now corrected.

2025-01-15 03:20 UTC, derekwaters commented on roles/aap_ocp_install/README.md
> +    aap_ocp_install_eda: true
I've added an install: true/false key to each of the components (controller, eda, hub), along with documentation in the readme.

2025-01-15 18:07 UTC, branic requested changes
@derekwaters Thanks for all your work on this. My testing has been successful.

I see one more minor change to the readme that is needed and then I will merge.

2025-01-15 18:07 UTC, branic commented on roles/aap_ocp_install/README.md
> +| instance_name | Yes      | None                             | Name of the AAP Platform instance to create     |
Can you document the `namespace` and `link_text` options here. You can just copy/paste from one of the other sections.

2025-01-15 19:46 UTC, branic approved these changes
Thanks @derekwaters.

2025-01-15 19:48 UTC, merged